---
abstract: 'Yet another on memory cache'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
  Test::Time: 0.04
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Cache-Memory-Simple
no_index:
  directory:
    - inc
provides:
  Cache::Memory::Simple:
    file: lib/Cache/Memory/Simple.pm
    version: 0.05
requires:
  Time::HiRes: 0
  parent: 0
  perl: 5.008001
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
